name: Publish on Docker Hub and Deploy

on:
  release:
    types: [published]

jobs:
  run_pub_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash
      - name: Run tests
        run: coverage run src/app_test.py
      - name: Tests report
        run: coverage report
  build_and_pub:
    needs: [run_pub_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      TAG: ${GITHUB_REF:10}
      TAG_LATEST: latest
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login --username ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:$TAG -f Dockerfile .
      - name: Push image tag [${TAG}] to docker.io
        run: docker push $LOGIN/$NAME:$TAG
      - name: Push image tag [latest] to docker.io
        run: docker push $LOGIN/$NAME:$TAG_LATEST
